name: Train & Deploy
on:
  push:
    branches: [ main ]

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install huggingface-hub

      - name: Train model
        run: python train.py

      - name: Deploy to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          huggingface-cli upload \
            asasdj/imdb-sentiment-nn \
            ./model \
            model \
            --token $HF_TOKEN

          huggingface-cli upload \
            asasdj/imdb-sentiment-nn \
            app.py \
            app.py \
            --token $HF_TOKEN

          huggingface-cli upload \
            asasdj/imdb-sentiment-nn \
            requirements.txt \
            requirements.txt \
            --token $HF_TOKEN
