name: Train & Deploy
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install huggingface-hub

      - name: Train model
        run: python train.py

      - name: Deploy to HF Space
        run: |
          huggingface-cli upload \
            asasdj/imdb-sentiment-nn \
            . \
            . \
            --include="app.py,requirements.txt,model/**/*" \
            --token ${{ secrets.HF_TOKEN }}
